/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as JsonFormatterRouteImport } from './routes/json-formatter'
import { Route as JsonMinifierRouteImport } from './routes/json-minifier'
import { Route as JsonToCsvRouteImport } from './routes/json-to-csv'
import { Route as JsonValidatorRouteImport } from './routes/json-validator'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonFormatterRoute = JsonFormatterRouteImport.update({
  id: '/json-formatter',
  path: '/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonMinifierRoute = JsonMinifierRouteImport.update({
  id: '/json-minifier',
  path: '/json-minifier',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonToCsvRoute = JsonToCsvRouteImport.update({
  id: '/json-to-csv',
  path: '/json-to-csv',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonValidatorRoute = JsonValidatorRouteImport.update({
  id: '/json-validator',
  path: '/json-validator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-minifier': typeof JsonMinifierRoute
  '/json-to-csv': typeof JsonToCsvRoute
  '/json-validator': typeof JsonValidatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-minifier': typeof JsonMinifierRoute
  '/json-to-csv': typeof JsonToCsvRoute
  '/json-validator': typeof JsonValidatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/json-minifier': typeof JsonMinifierRoute
  '/json-to-csv': typeof JsonToCsvRoute
  '/json-validator': typeof JsonValidatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/json-formatter'
    | '/json-minifier'
    | '/json-to-csv'
    | '/json-validator'
    | '/privacy-policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/json-formatter'
    | '/json-minifier'
    | '/json-to-csv'
    | '/json-validator'
    | '/privacy-policy'
  id:
    | '__root__'
    | '/'
    | '/cookie-policy'
    | '/json-formatter'
    | '/json-minifier'
    | '/json-to-csv'
    | '/json-validator'
    | '/privacy-policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  JsonFormatterRoute: typeof JsonFormatterRoute
  JsonMinifierRoute: typeof JsonMinifierRoute
  JsonToCsvRoute: typeof JsonToCsvRoute
  JsonValidatorRoute: typeof JsonValidatorRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-formatter': {
      id: '/json-formatter'
      path: '/json-formatter'
      fullPath: '/json-formatter'
      preLoaderRoute: typeof JsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-minifier': {
      id: '/json-minifier'
      path: '/json-minifier'
      fullPath: '/json-minifier'
      preLoaderRoute: typeof JsonMinifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-to-csv': {
      id: '/json-to-csv'
      path: '/json-to-csv'
      fullPath: '/json-to-csv'
      preLoaderRoute: typeof JsonToCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-validator': {
      id: '/json-validator'
      path: '/json-validator'
      fullPath: '/json-validator'
      preLoaderRoute: typeof JsonValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  JsonFormatterRoute: JsonFormatterRoute,
  JsonMinifierRoute: JsonMinifierRoute,
  JsonToCsvRoute: JsonToCsvRoute,
  JsonValidatorRoute: JsonValidatorRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
